export default {
  FETCH_PRICE_REQUESTED: "FETCH_PRICE_REQUESTED",
  FETCH_PRICE_SUCCEEDED: "FETCH_PRICE_SUCCEEDED",
  FETCH_PRICE_FAILED: "FETCH_PRICE_FAILED",
  UPDATE_PRICE_REQUESTED: "UPDATE_PRICE_REQUESTED",
  UPDATE_PRICE_SUCCEEDED: "UPDATE_PRICE_SUCCEEDED",
  UPDATE_PRICE_FAILED: "UPDATE_PRICE_FAILED"
};
